// Auto-generated extra Bengali vocabulary for Alias Jimmy Valentine
(function(){
  const EXTRA = {
"ability":{word:"ability",pronunciation:"/əˈbɪləti/",pos:"Noun",bn:"ক্ষমতা / সামর্থ্য",en:"Skill or power to do something.",context:"His ability to crack safes.",example:"Natural ability."},
"adams":{word:"Adams",pronunciation:"/ˈædəmz/",pos:"Proper Noun",bn:"অ্যাডামস (ব্যাংকার)",en:"Mr. Adams, the banker.",context:"Annabel's father.",example:"Mr. Adams owned the bank."},
"against":{word:"against",pronunciation:"/əˈɡenst/",pos:"Preposition",bn:"বিরুদ্ধে / বিপরীতে",en:"In opposition to.",context:"Buck against the law.",example:"Against the wall."},
"agatha":{word:"Agatha",pronunciation:"/ˈæɡəθə/",pos:"Proper Noun",bn:"অ্যাগাথা",en:"Annabel's young niece.",context:"The child locked in the vault.",example:"Little Agatha was trapped."},
"alias":{word:"alias",pronunciation:"/ˈeɪliəs/",pos:"Noun",bn:"ছদ্মনাম / উপনাম",en:"A false name used by a person.",context:"Jimmy uses an alias.",example:"He lived under an alias."},
"annabel":{word:"Annabel",pronunciation:"/ˈænəbel/",pos:"Proper Noun",bn:"অ্যানাবেল",en:"Jimmy's fiancée.",context:"Daughter of Mr. Adams.",example:"Annabel Adams loved Ralph."},
"another":{word:"another",pronunciation:"/əˈnʌðər/",pos:"Determiner",bn:"আরেকটি / অন্য",en:"One more; a different one.",context:"Another chance.",example:"Try another way."},
"around":{word:"around",pronunciation:"/əˈraʊnd/",pos:"Adverb/Preposition",bn:"চারপাশে / আশেপাশে",en:"In the vicinity.",context:"Look around.",example:"Around the town."},
"bank":{word:"bank",pronunciation:"/bæŋk/",pos:"Noun",bn:"ব্যাংক",en:"A financial institution.",context:"The bank vault.",example:"He robbed banks."},
"became":{word:"became",pronunciation:"/bɪˈkeɪm/",pos:"Verb",bn:"হয়ে উঠল",en:"Past of become.",context:"He became Ralph Spencer.",example:"She became silent."},
"began":{word:"began",pronunciation:"/bɪˈɡæn/",pos:"Verb",bn:"শুরু করল",en:"Past of begin.",context:"He began a new life.",example:"The work began."},
"ben":{word:"Ben",pronunciation:"/ben/",pos:"Proper Noun",bn:"বেন (গোয়েন্দা)",en:"Detective Ben Price.",context:"The detective who tracks Jimmy.",example:"Ben Price recognized Jimmy."},
"blending":{word:"blending",pronunciation:"/ˈblendɪŋ/",pos:"Verb",bn:"মিশ্রণ / মিলিত করা",en:"Mixing together.",context:"Blending wit and irony.",example:"Blending styles."},
"boy":{word:"boy",pronunciation:"/bɔɪ/",pos:"Noun",bn:"ছেলে",en:"A male child.",context:"A little boy.",example:"The boy cried."},
"business":{word:"business",pronunciation:"/ˈbɪznəs/",pos:"Noun",bn:"ব্যবসা",en:"Trade or commercial activity.",context:"The shoe business.",example:"A successful business."},
"came":{word:"came",pronunciation:"/keɪm/",pos:"Verb",bn:"এল / এসেছিল",en:"Past of come.",context:"He came to Elmore.",example:"She came in."},
"child":{word:"child",pronunciation:"/tʃaɪld/",pos:"Noun",bn:"শিশু / সন্তান",en:"A young person.",context:"A small child.",example:"Mother and child."},
"citizen":{word:"citizen",pronunciation:"/ˈsɪtɪzn/",pos:"Noun",bn:"নাগরিক",en:"A member of a community or nation.",context:"Become a good citizen.",example:"A law-abiding citizen."},
"clever":{word:"clever",pronunciation:"/ˈklevər/",pos:"Adjective",bn:"চতুর / বুদ্ধিমান",en:"Quick to understand; skillful.",context:"A clever narrative.",example:"He is clever."},
"crime":{word:"crime",pronunciation:"/kraɪm/",pos:"Noun",bn:"অপরাধ",en:"An illegal act.",context:"He gave up crime.",example:"A serious crime."},
"criminal":{word:"criminal",pronunciation:"/ˈkrɪmɪnl/",pos:"Noun/Adjective",bn:"অপরাধী / অপরাধমূলক",en:"A person who commits crime.",context:"His criminal past.",example:"A wanted criminal."},
"deep":{word:"deep",pronunciation:"/diːp/",pos:"Adjective",bn:"গভীর",en:"Extending far down; intense.",context:"Deep emotions.",example:"A deep vault."},
"detective":{word:"detective",pronunciation:"/dɪˈtektɪv/",pos:"Noun",bn:"গোয়েন্দা",en:"A person who investigates crimes.",context:"Ben Price is a detective.",example:"The detective arrived."},
"dolan":{word:"Dolan",pronunciation:"/ˈdəʊlən/",pos:"Proper Noun",bn:"ডোলান",en:"Mike Dolan.",context:"Owner of a café/hangout.",example:"Mike Dolan's place."},
"dollars":{word:"dollars",pronunciation:"/ˈdɒlərz/",pos:"Noun",bn:"ডলার",en:"US currency.",context:"Thousands of dollars.",example:"Five thousand dollars."},
"door":{word:"door",pronunciation:"/dɔːr/",pos:"Noun",bn:"দরজা",en:"An entrance to a room or building.",context:"He opened the door.",example:"The vault door was shut."},
"elmore":{word:"Elmore",pronunciation:"/ˈelmɔːr/",pos:"Proper Noun",bn:"এলমোর (শহর)",en:"A small town in Arkansas.",context:"Where Jimmy settles as Ralph Spencer.",example:"He went to Elmore."},
"five":{word:"five",pronunciation:"/faɪv/",pos:"Number",bn:"পাঁচ",en:"The number 5.",context:"Five thousand dollars.",example:"Five minutes."},
"gave":{word:"gave",pronunciation:"/ɡeɪv/",pos:"Verb",bn:"দিল / প্রদান করল",en:"Past of give.",context:"He gave up crime.",example:"She gave a cry."},
"get":{word:"get",pronunciation:"/ɡet/",pos:"Verb",bn:"পাওয়া / যাওয়া",en:"To obtain or become.",context:"Get the tools.",example:"He got free."},
"given":{word:"given",pronunciation:"/ˈɡɪvn/",pos:"Verb",bn:"দেওয়া হয়েছে",en:"Past participle of give.",context:"Given a chance.",example:"Given the circumstances."},
"go":{word:"go",pronunciation:"/ɡəʊ/",pos:"Verb",bn:"যাওয়া",en:"To move or travel.",context:"Go free.",example:"I must go."},
"going":{word:"going",pronunciation:"/ˈɡəʊɪŋ/",pos:"Verb",bn:"যাচ্ছে",en:"Present participle of go.",context:"He was going away.",example:"She is going home."},
"got":{word:"got",pronunciation:"/ɡɒt/",pos:"Verb",bn:"পেল / গেল",en:"Past of get.",context:"He got a new identity.",example:"She got the letter."},
"hand":{word:"hand",pronunciation:"/hænd/",pos:"Noun",bn:"হাত",en:"Body part at end of arm.",context:"In his hand.",example:"Give me a hand."},
"heard":{word:"heard",pronunciation:"/hɜːrd/",pos:"Verb",bn:"শুনল",en:"Past of hear.",context:"He heard a cry.",example:"She heard the news."},
"henry":{word:"Henry",pronunciation:"/ˈhenri/",pos:"Proper Noun",bn:"হেনরি (লেখক)",en:"O. Henry, the author.",context:"Written by O. Henry.",example:"O. Henry's story."},
"himself":{word:"himself",pronunciation:"/hɪmˈself/",pos:"Pronoun",bn:"নিজে / স্বয়ং",en:"Reflexive form of he.",context:"He locked himself in.",example:"Jimmy blamed himself."},
"honest":{word:"honest",pronunciation:"/ˈɒnɪst/",pos:"Adjective",bn:"সৎ",en:"Truthful; not criminal.",context:"An honest businessman.",example:"Be honest."},
"human":{word:"human",pronunciation:"/ˈhjuːmən/",pos:"Adjective/Noun",bn:"মানব / মানবিক",en:"Relating to people.",context:"Human nature.",example:"A human being."},
"hundred":{word:"hundred",pronunciation:"/ˈhʌndrəd/",pos:"Number",bn:"শত / একশ",en:"The number 100.",context:"A hundred dollars.",example:"One hundred years."},
"insight":{word:"insight",pronunciation:"/ˈɪnsaɪt/",pos:"Noun",bn:"অন্তর্দৃষ্টি / উপলব্ধি",en:"Deep understanding.",context:"Psychological insight.",example:"A moment of insight."},
"irony":{word:"irony",pronunciation:"/ˈaɪrəni/",pos:"Noun",bn:"বিদ্রূপ / পরিহাস",en:"Contrast between expectation and reality.",context:"Dramatic irony in the ending.",example:"The irony of fate."},
"jimmy":{word:"Jimmy",pronunciation:"/ˈdʒɪmi/",pos:"Proper Noun",bn:"জিমি (প্রধান চরিত্র)",en:"The main character; a skilled safe-cracker.",context:"Jimmy Valentine is the protagonist.",example:"Jimmy changed his life for love."},
"joys":{word:"joys",pronunciation:"/dʒɔɪz/",pos:"Noun",bn:"আনন্দসমূহ",en:"Plural of joy; pleasures.",context:"Simple joys of life.",example:"Childhood joys."},
"know":{word:"know",pronunciation:"/nəʊ/",pos:"Verb",bn:"জানা",en:"To be aware of.",context:"I know him.",example:"Do you know the truth?"},
"lady":{word:"lady",pronunciation:"/ˈleɪdi/",pos:"Noun",bn:"মহিলা / ভদ্রমহিলা",en:"A woman of good manners.",context:"A young lady.",example:"Ladies and gentlemen."},
"life":{word:"life",pronunciation:"/laɪf/",pos:"Noun",bn:"জীবন",en:"Existence; way of living.",context:"A new life.",example:"He changed his life."},
"light":{word:"light",pronunciation:"/laɪt/",pos:"Noun/Adjective",bn:"আলো / হালকা",en:"Illumination; not heavy.",context:"Turn on the light.",example:"A light touch."},
"like":{word:"like",pronunciation:"/laɪk/",pos:"Preposition/Verb",bn:"মতো / পছন্দ করা",en:"Similar to; to enjoy.",context:"Opened like a cheese.",example:"He liked the town."},
"line":{word:"line",pronunciation:"/laɪn/",pos:"Noun",bn:"লাইন / সারি / ব্যবসা",en:"A row; a trade.",context:"In the shoe line.",example:"A telephone line."},
"look":{word:"look",pronunciation:"/lʊk/",pos:"Verb",bn:"দেখা / তাকানো",en:"To direct the eyes.",context:"Look at the safe.",example:"She looked worried."},
"looking":{word:"looking",pronunciation:"/ˈlʊkɪŋ/",pos:"Verb",bn:"তাকিয়ে / দেখতে",en:"Present participle of look.",context:"Looking for a job.",example:"Good-looking man."},
"love":{word:"love",pronunciation:"/lʌv/",pos:"Noun/Verb",bn:"ভালোবাসা",en:"Deep affection.",context:"Love reformed Jimmy.",example:"He fell in love."},
"made":{word:"made",pronunciation:"/meɪd/",pos:"Verb",bn:"তৈরি করল / করল",en:"Past of make.",context:"He made a decision.",example:"Made of steel."},
"make":{word:"make",pronunciation:"/meɪk/",pos:"Verb",bn:"তৈরি করা / করা",en:"To create or cause.",context:"Make a living.",example:"Don't make noise."},
"man":{word:"man",pronunciation:"/mæn/",pos:"Noun",bn:"মানুষ / পুরুষ",en:"An adult male person.",context:"A man entered the bank.",example:"The young man smiled."},
"married":{word:"married",pronunciation:"/ˈmærid/",pos:"Adjective/Verb",bn:"বিবাহিত / বিয়ে করা",en:"United in marriage.",context:"They got married.",example:"A married man."},
"mike":{word:"Mike",pronunciation:"/maɪk/",pos:"Proper Noun",bn:"মাইক",en:"A fellow prisoner / associate.",context:"Mike Dolan's place.",example:"Mike spoke to Jimmy."},
"miss":{word:"Miss",pronunciation:"/mɪs/",pos:"Noun",bn:"মিশ (অবিবাহিতা সম্বোধন)",en:"Title for an unmarried woman.",context:"Miss Annabel Adams.",example:"Yes, Miss."},
"mother":{word:"mother",pronunciation:"/ˈmʌðər/",pos:"Noun",bn:"মা",en:"Female parent.",context:"Her mother smiled.",example:"Mother and child."},
"mr":{word:"Mr.",pronunciation:"/ˈmɪstər/",pos:"Title",bn:"মিস্টার (পুরুষ সম্বোধন)",en:"Title before a man's name.",context:"Mr. Adams.",example:"Mr. Spencer."},
"nature":{word:"nature",pronunciation:"/ˈneɪtʃər/",pos:"Noun",bn:"প্রকৃতি / স্বভাব",en:"The natural world; character.",context:"Human nature.",example:"By nature."},
"nice":{word:"nice",pronunciation:"/naɪs/",pos:"Adjective",bn:"সুন্দর / ভালো",en:"Pleasant; agreeable.",context:"A nice town.",example:"Nice to meet you."},
"nine":{word:"nine",pronunciation:"/naɪn/",pos:"Number",bn:"নয়",en:"The number 9.",context:"Nine years sentence.",example:"At nine o'clock."},
"one":{word:"one",pronunciation:"/wʌn/",pos:"Number/Pronoun",bn:"এক / একজন",en:"The number 1; a person.",context:"One day.",example:"The one he loved."},
"open":{word:"open",pronunciation:"/ˈəʊpən/",pos:"Verb/Adjective",bn:"খোলা / উন্মুক্ত",en:"Not closed; to unclose.",context:"Open the safe.",example:"An open door."},
"opened":{word:"opened",pronunciation:"/ˈəʊpənd/",pos:"Verb",bn:"খুলল / খোলা হল",en:"Past of open.",context:"Jimmy opened safes.",example:"The door opened."},
"pardon":{word:"pardon",pronunciation:"/ˈpɑːrdn/",pos:"Noun",bn:"ক্ষমা / মার্জনা",en:"Official forgiveness of a crime.",context:"Jimmy received a pardon.",example:"A presidential pardon."},
"past":{word:"past",pronunciation:"/pɑːst/",pos:"Noun/Adjective",bn:"অতীত",en:"Time gone by.",context:"His criminal past.",example:"In the past."},
"place":{word:"place",pronunciation:"/pleɪs/",pos:"Noun",bn:"জায়গা / স্থান",en:"A location.",context:"A quiet place.",example:"Take your place."},
"price":{word:"Price",pronunciation:"/praɪs/",pos:"Proper Noun",bn:"প্রাইস (গোয়েন্দার নাম)",en:"Surname of the detective.",context:"Ben Price is the detective.",example:"Mr. Price followed him."},
"prison":{word:"prison",pronunciation:"/ˈprɪzn/",pos:"Noun",bn:"কারাগার / জেল",en:"A place of confinement.",context:"Released from prison.",example:"Prison walls."},
"pulling":{word:"pulling",pronunciation:"/ˈpʊlɪŋ/",pos:"Verb",bn:"টানা",en:"Present participle of pull.",context:"Pulling the door.",example:"Pulling strings."},
"put":{word:"put",pronunciation:"/pʊt/",pos:"Verb",bn:"রাখা / স্থাপন করা",en:"To place something.",context:"Put the tools away.",example:"He put on a suit."},
"ralph":{word:"Ralph",pronunciation:"/rælf/",pos:"Proper Noun",bn:"র‍্যাল্ফ (ছদ্মনাম)",en:"Ralph D. Spencer — Jimmy's honest identity.",context:"Jimmy becomes Ralph Spencer.",example:"Ralph Spencer owned the shoe-store."},
"release":{word:"release",pronunciation:"/rɪˈliːs/",pos:"Noun/Verb",bn:"মুক্তি / মুক্ত করা",en:"Setting free.",context:"His release from prison.",example:"Release the prisoner."},
"rock":{word:"rock",pronunciation:"/rɒk/",pos:"Noun",bn:"পাথর / শিলা",en:"A hard mineral mass.",context:"A rock of the vault.",example:"Solid as a rock."},
"room":{word:"room",pronunciation:"/ruːm/",pos:"Noun",bn:"ঘর / কক্ষ",en:"A space in a building.",context:"The hotel room.",example:"Enter the room."},
"safe":{word:"safe",pronunciation:"/seɪf/",pos:"Noun/Adjective",bn:"সিন্দুক / নিরাপদ",en:"A strong box; free from danger.",context:"Jimmy cracked safes.",example:"A burglar-proof safe."},
"said":{word:"said",pronunciation:"/sed/",pos:"Verb",bn:"বলল / বলেছিল",en:"Past tense of say.",context:"Used in dialogue.",example:"He said nothing."},
"serving":{word:"serving",pronunciation:"/ˈsɜːrvɪŋ/",pos:"Verb",bn:"সেবা করা / সাজা ভোগ করা",en:"Performing duty; undergoing sentence.",context:"Serving a prison term.",example:"Serving the community."},
"set":{word:"set",pronunciation:"/set/",pos:"Verb/Noun",bn:"স্থাপন করা / সেট",en:"To place; a collection.",context:"He set the tools down.",example:"A set of tools."},
"shoe-store":{word:"shoe-store",pronunciation:"/ˈʃuː stɔːr/",pos:"Noun",bn:"জুতার দোকান",en:"A shop selling shoes.",context:"Ralph ran a shoe-store.",example:"The shoe-store flourished."},
"shook":{word:"shook",pronunciation:"/ʃʊk/",pos:"Verb",bn:"কাঁপাল / নাড়াল",en:"Past of shake.",context:"He shook his head.",example:"The ground shook."},
"something":{word:"something",pronunciation:"/ˈsʌmθɪŋ/",pos:"Pronoun",bn:"কিছু একটা",en:"An unspecified thing.",context:"Something happened.",example:"He wanted something better."},
"spencer":{word:"Spencer",pronunciation:"/ˈspensər/",pos:"Proper Noun",bn:"স্পেন্সার",en:"Ralph D. Spencer.",context:"Jimmy's new name in Elmore.",example:"Mr. Spencer was respected."},
"springfield":{word:"Springfield",pronunciation:"/ˈsprɪŋfiːld/",pos:"Proper Noun",bn:"স্প্রিংফিল্ড",en:"A city mentioned in the story.",context:"Site of a bank job.",example:"The Springfield job."},
"store":{word:"store",pronunciation:"/stɔːr/",pos:"Noun",bn:"দোকান",en:"A shop.",context:"The shoe-store.",example:"Open a store."},
"stories":{word:"stories",pronunciation:"/ˈstɔːriz/",pos:"Noun",bn:"গল্পসমূহ",en:"Plural of story.",context:"Short stories.",example:"His stories are famous."},
"story":{word:"story",pronunciation:"/ˈstɔːri/",pos:"Noun",bn:"গল্প / কাহিনি",en:"A narrative.",context:"This is the story.",example:"A short story."},
"storytelling":{word:"storytelling",pronunciation:"/ˈstɔːritelɪŋ/",pos:"Noun",bn:"গল্প বলা / কাহিনি বর্ণনা",en:"The art of telling stories.",context:"Master of storytelling.",example:"Oral storytelling."},
"strong":{word:"strong",pronunciation:"/strɒŋ/",pos:"Adjective",bn:"শক্তিশালী / মজবুত",en:"Having power; sturdy.",context:"A strong lock.",example:"Strong enough."},
"suit":{word:"suit",pronunciation:"/suːt/",pos:"Noun",bn:"স্যুট / পোশাক",en:"A set of clothes.",context:"A business suit.",example:"He wore a suit."},
"thought":{word:"thought",pronunciation:"/θɔːt/",pos:"Verb/Noun",bn:"ভাবল / চিন্তা",en:"Past of think; an idea.",context:"He thought of Annabel.",example:"A sudden thought."},
"three":{word:"three",pronunciation:"/θriː/",pos:"Number",bn:"তিন",en:"The number 3.",context:"Three minutes.",example:"Three people."},
"time":{word:"time",pronunciation:"/taɪm/",pos:"Noun",bn:"সময়",en:"Duration; occasion.",context:"A short time.",example:"It was time to leave."},
"took":{word:"took",pronunciation:"/tʊk/",pos:"Verb",bn:"নিল / নিয়ে গেল",en:"Past of take.",context:"He took the tools.",example:"It took time."},
"tools":{word:"tools",pronunciation:"/tuːlz/",pos:"Noun",bn:"যন্ত্রপাতি / সরঞ্জাম",en:"Instruments for work.",context:"Jimmy's burglar tools.",example:"A kit of tools."},
"town":{word:"town",pronunciation:"/taʊn/",pos:"Noun",bn:"শহর / নগর",en:"A populated place smaller than a city.",context:"Elmore is a small town.",example:"He settled in the town."},
"trapped":{word:"trapped",pronunciation:"/træpt/",pos:"Verb/Adjective",bn:"আটকা পড়া",en:"Caught and unable to escape.",context:"The child was trapped.",example:"Trapped inside."},
"twist":{word:"twist",pronunciation:"/twɪst/",pos:"Noun",bn:"মোড় / অপ্রত্যাশিত পরিণতি",en:"An unexpected turn.",context:"Twist ending.",example:"A plot twist."},
"two":{word:"two",pronunciation:"/tuː/",pos:"Number",bn:"দুই",en:"The number 2.",context:"Two children were playing.",example:"It took two minutes."},
"valentine":{word:"Valentine",pronunciation:"/ˈvæləntaɪn/",pos:"Proper Noun",bn:"ভ্যালেন্টাইন (উপনাম)",en:"Jimmy's surname as a criminal.",context:"His criminal alias.",example:"Alias Jimmy Valentine."},
"vault":{word:"vault",pronunciation:"/vɔːlt/",pos:"Noun",bn:"তহবিল কক্ষ / ভল্ট",en:"A secure room for valuables.",context:"The bank vault trapped Agatha.",example:"Open the vault."},
"walked":{word:"walked",pronunciation:"/wɔːkt/",pos:"Verb",bn:"হাঁটল",en:"Past of walk.",context:"He walked away.",example:"She walked in."},
"want":{word:"want",pronunciation:"/wɒnt/",pos:"Verb",bn:"চাওয়া",en:"To desire.",context:"I want a new life.",example:"They want him free."},
"way":{word:"way",pronunciation:"/weɪ/",pos:"Noun",bn:"পথ / উপায়",en:"A path or method.",context:"On the way.",example:"Find a way."},
"weeks":{word:"weeks",pronunciation:"/wiːks/",pos:"Noun",bn:"সপ্তাহসমূহ",en:"Plural of week.",context:"For several weeks.",example:"Two weeks later."},
"went":{word:"went",pronunciation:"/went/",pos:"Verb",bn:"গেল / গিয়েছিল",en:"Past tense of go.",context:"Movement in the story.",example:"He went to Elmore."},
"while":{word:"while",pronunciation:"/waɪl/",pos:"Conjunction/Noun",bn:"যখন / কিছুক্ষণ",en:"During the time that.",context:"While he worked.",example:"Wait a while."},
"wit":{word:"wit",pronunciation:"/wɪt/",pos:"Noun",bn:"বুদ্ধিদীপ্ত রসিকতা",en:"Clever humor.",context:"Full of wit.",example:"Quick wit."},
"year":{word:"year",pronunciation:"/jɪər/",pos:"Noun",bn:"বছর",en:"Twelve months.",context:"For a year.",example:"Next year."},
"young":{word:"young",pronunciation:"/jʌŋ/",pos:"Adjective",bn:"তরুণ / যুবক",en:"Not old; youthful.",context:"A young lady.",example:"The young man left."}
  };
  if (typeof VOCABULARY !== 'undefined') {
    Object.assign(VOCABULARY, EXTRA);
  } else {
    window.__VOCAB_EXTRA__ = EXTRA;
  }
})();
